"""purchase extended from

Revision ID: 073b2167bbda
Revises: d60abd12c0ed
Create Date: 2026-07-31 15:42:30.332453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.models.base import UtcDateTime


# revision identifiers, used by Alembic.
revision: str = '073b2167bbda'
down_revision: Union[str, Sequence[str], None] = 'd60abd12c0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extended_from', UtcDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('extended_from')

    # ### end Alembic commands ###
