"""referral links

Revision ID: 3a0ee2eba94d
Revises: f31a86a33e7d
Create Date: 2026-08-09 10:37:42.744354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Alembic autogenerate emits `api.models.base.UtcDateTime(...)` and never imports it. Fifth
# time in this project; `alembic upgrade` dies with NameError without this line, and that
# command runs on every api container start, so the deploy comes up in a crash loop.
import api.models.base


# revision identifiers, used by Alembic.
revision: str = '3a0ee2eba94d'
down_revision: Union[str, Sequence[str], None] = 'f31a86a33e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_links',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('created_at', api.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_links')
    # ### end Alembic commands ###
