"""quiz sessions: exam and practice sittings

Revision ID: 4b12f455fb2d
Revises: c7a3e91f4d28
Create Date: 2026-07-30 21:22:52.444750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate emits the fully-qualified name of the custom type but does not import it.
from api.models.base import UtcDateTime


# revision identifiers, used by Alembic.
revision: str = '4b12f455fb2d'
down_revision: Union[str, Sequence[str], None] = 'c7a3e91f4d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('started_at', UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', UtcDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', UtcDateTime(timezone=True), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('max_errors', sa.Integer(), nullable=True),
    sa.Column('answered', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['users.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_sessions_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index('ix_session_open', ['chat_id', 'state'], unique=False)

    op.create_table('quiz_session_items',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('given', sa.Boolean(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'ordinal')
    )
    with op.batch_alter_table('quiz_session_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_session_items_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_session_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_session_items_question_id'))

    op.drop_table('quiz_session_items')
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_open')
        batch_op.drop_index(batch_op.f('ix_quiz_sessions_chat_id'))

    op.drop_table('quiz_sessions')
    # ### end Alembic commands ###
