"""initial schema

Revision ID: 4bafdede07a8
Revises: 
Create Date: 2026-07-29 17:11:28.670340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bafdede07a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_event_chat_time', ['chat_id', 'created_at'], unique=False)
        batch_op.create_index('ix_event_type_time', ['type', 'created_at'], unique=False)

    op.create_table('figures',
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('path')
    )
    with op.batch_alter_table('figures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_figures_sha256'), ['sha256'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('tribute_purchase_id', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('extended_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tribute_purchase_id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_created_at'), ['created_at'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('translations_on', sa.Boolean(), nullable=False),
    sa.Column('pass_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('free_explanations_used', sa.Integer(), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_pass_expires_at'), ['pass_expires_at'], unique=False)

    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('rule_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_topic_id'), ['topic_id'], unique=False)

    op.create_table('quesiti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('primary_image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['primary_image'], ['figures.path'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quesiti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quesiti_topic_id'), ['topic_id'], unique=False)

    op.create_table('explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'lang', name='uq_explanation_lang')
    )
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.create_index('ix_explanation_lookup', ['cluster_id', 'lang', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_explanations_status'), ['status'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quesito_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('stem_it', sa.Text(), nullable=True),
    sa.Column('statement_it', sa.Text(), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('source_version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['image_path'], ['figures.path'], ),
    sa.ForeignKeyConstraint(['quesito_id'], ['quesiti.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_quesito_id'), ['quesito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source_version'), ['source_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('progress',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('last_answer_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['users.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'question_id')
    )
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index('ix_progress_due', ['chat_id', 'due_at'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)

    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'lang', name='uq_translation_lang')
    )
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translations_lang'), ['lang'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translations_lang'))

    op.drop_table('translations')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_reports_chat_id'))

    op.drop_table('reports')
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index('ix_progress_due')

    op.drop_table('progress')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_questions_source_version'))
        batch_op.drop_index(batch_op.f('ix_questions_quesito_id'))
        batch_op.drop_index(batch_op.f('ix_questions_cluster_id'))

    op.drop_table('questions')
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explanations_status'))
        batch_op.drop_index('ix_explanation_lookup')

    op.drop_table('explanations')
    with op.batch_alter_table('quesiti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quesiti_topic_id'))

    op.drop_table('quesiti')
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_topic_id'))

    op.drop_table('clusters')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_pass_expires_at'))

    op.drop_table('users')
    op.drop_table('topics')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchases_chat_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('figures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_figures_sha256'))

    op.drop_table('figures')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_type_time')
        batch_op.drop_index('ix_event_chat_time')

    op.drop_table('events')
    # ### end Alembic commands ###
