"""vocabulary trainer

Revision ID: 62f2935d159b
Revises: 4b12f455fb2d
Create Date: 2026-07-31 07:52:04.393653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.models.base import UtcDateTime


# revision identifiers, used by Alembic.
revision: str = '62f2935d159b'
down_revision: Union[str, Sequence[str], None] = '4b12f455fb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('it', sa.Text(), nullable=False),
    sa.Column('en', sa.Text(), nullable=False),
    sa.Column('ru', sa.Text(), nullable=False),
    sa.Column('uz', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('it', name='uq_vocab_term_it')
    )
    with op.batch_alter_table('vocab_terms', schema=None) as batch_op:
        batch_op.create_index('ix_vocab_rank', ['rank'], unique=False)

    op.create_table('vocab_progress',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('due_at', UtcDateTime(timezone=True), nullable=False),
    sa.Column('seen', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('almost', sa.Integer(), nullable=False),
    sa.Column('last_answer_at', UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['users.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['vocab_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'term_id')
    )
    with op.batch_alter_table('vocab_progress', schema=None) as batch_op:
        batch_op.create_index('ix_vocab_progress_due', ['chat_id', 'due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_vocab_progress_due')

    op.drop_table('vocab_progress')
    with op.batch_alter_table('vocab_terms', schema=None) as batch_op:
        batch_op.drop_index('ix_vocab_rank')

    op.drop_table('vocab_terms')
    # ### end Alembic commands ###
