"""generated_at on explanations and translations

Revision ID: 87c8dcf00671
Revises: 3a0ee2eba94d
Create Date: 2026-08-09 12:14:18.079521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Sixth time. Autogenerate emits `api.models.base.UtcDateTime(...)` and never imports it,
# and `alembic upgrade` runs on every api container start — so without this line the deploy
# comes up in a crash loop rather than failing where anyone can see it.
import api.models.base


# revision identifiers, used by Alembic.
revision: str = '87c8dcf00671'
down_revision: Union[str, Sequence[str], None] = '3a0ee2eba94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_at', api.models.base.UtcDateTime(timezone=True), nullable=True))

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_at', api.models.base.UtcDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_column('generated_at')

    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.drop_column('generated_at')

    # ### end Alembic commands ###
