"""channel membership cache

Revision ID: ae32d9e20adf
Revises: 62f2935d159b
Create Date: 2026-07-31 11:16:46.388104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.models.base import UtcDateTime


# revision identifiers, used by Alembic.
revision: str = 'ae32d9e20adf'
down_revision: Union[str, Sequence[str], None] = '62f2935d159b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('channel_checked_at', UtcDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('channel_checked_at')
        batch_op.drop_column('channel_status')

    # ### end Alembic commands ###
