"""webhook deliveries

Revision ID: d60abd12c0ed
Revises: 514e575ed2aa
Create Date: 2026-07-31 15:27:08.639549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.models.base import UtcDateTime


# revision identifiers, used by Alembic.
revision: str = 'd60abd12c0ed'
down_revision: Union[str, Sequence[str], None] = '514e575ed2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('signature_ok', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index('ix_webhook_received', ['received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_webhook_received')
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_chat_id'))

    op.drop_table('webhook_deliveries')
    # ### end Alembic commands ###
