"""leaderboard and streak freezes

Revision ID: f31a86a33e7d
Revises: 073b2167bbda
Create Date: 2026-07-31 18:47:50.319620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31a86a33e7d'
down_revision: Union[str, Sequence[str], None] = '073b2167bbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    `server_default` on both NOT NULL columns, and autogenerate does not add them.

    A NOT NULL column with no default cannot be added to a table that already has rows —
    there is nothing to put in them — and `users` has real rows in production. Without these
    the migration fails at `alembic upgrade head`, which runs on every api container start,
    so the deploy would come up in a crash loop rather than failing visibly.

    The defaults are also the honest values: nobody has opted out until they say so, and
    nobody has earned a freeze yet.
    """
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column(
            'leaderboard_opt_out', sa.Boolean(), nullable=False,
            server_default=sa.text('0')))
        batch_op.add_column(sa.Column(
            'streak_freezes', sa.Integer(), nullable=False,
            server_default=sa.text('0')))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('streak_freezes')
        batch_op.drop_column('leaderboard_opt_out')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
